# Generated by Django 2.2 on 2019-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('tid', models.CharField(max_length=20)),
                ('tname', models.CharField(max_length=20)),
                ('isValid', models.BinaryField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('permission', models.IntegerField()),
            ],
        ),
    ]
