# Generated by Django 2.2 on 2019-05-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='list_time',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
