# Generated by Django 2.2 on 2019-05-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import homework.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('coid', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=0)),
                ('homework_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('filepath', models.FileField(upload_to=homework.models.user_directory_path)),
                ('num', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
