# Generated by Django 2.2 on 2019-05-19 12:48

from django.db import migrations, models
import homework.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20190518_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='filepath',
            field=models.FileField(default='', upload_to=homework.models.user_directory_path),
        ),
    ]
