# Generated by Django 2.2 on 2019-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20190519_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_file',
            field=models.BooleanField(default=0),
        ),
    ]
