# Generated by Django 2.2 on 2019-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homework_is_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_correct',
            field=models.BooleanField(default=0),
        ),
    ]
