# Generated by Django 2.2 on 2019-05-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField()),
                ('details', models.CharField(max_length=1000)),
                ('course_time', models.CharField(max_length=200)),
                ('course_loc', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ManyToManyField(related_name='users', to='course.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assistants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ManyToManyField(related_name='assistants', to='course.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_assistant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_applications', to='course.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
